"""first migration

Revision ID: 002c220c3b18
Revises: 
Create Date: 2021-04-24 18:51:09.478526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002c220c3b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
